language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7

matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7
    - python: 3.2
      env: DJANGO=1.4
    - python: 3.3
      env: DJANGO=1.4
    - python: 3.4
      env: DJANGO=1.4
    - python: 3.4
      env: DJANGO=1.5
    - python: 3.4
      env: DJANGO=1.6
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: 3.4

install:
  - pip install tox coveralls

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - tox -e `python -c 'import sys,os;print("py%d%d-"%sys.version_info[0:2]+os.environ["DJANGO"])'`

after_success:
  - coverage report -m
  - coveralls
