language: python

python:
  - 2.6
  - 2.7
  
env:
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="https://github.com/django/django/archive/stable/1.5.x.tar.gz"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

install:
  - pip install $DJANGO selenium -q --use-mirrors

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - django-admin.py test admin_enhancer --settings=test_settings --pythonpath=`pwd`
